kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/jnummelin/s3-url-signer


steps:
- name: build
  image: golang:1.11
  commands:
  - mkdir -p /go/bin
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure -vendor-only
  - ./build.sh # just try to build, no real tests exist :)

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - output/*
    draft: true # Add changelog and publish manually
    checksum:
      - sha256
  when:
    event: tag